use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process;

struct LintEntry {
    name_snake: String,
    name_doc: String,
    level: String,
    description: String,
    category: Option<String>,
}

fn parse_lib_rs(content: &str) -> Vec<LintEntry> {
    let lines: Vec<&str> = content.lines().collect();
    let mut entries: Vec<LintEntry> = Vec::new();
    let mut i = 0;

    while i < lines.len() {
        let trimmed = lines[i].trim();
        if trimmed.contains("declare_lint!") && trimmed.ends_with('{') {
            i += 1;
            while i < lines.len() && lines[i].trim().is_empty() {
                i += 1;
            }
            let name_line = lines[i].trim();
            if !name_line.starts_with("pub ") {
                i += 1;
                continue;
            }
            let name_snake = name_line
                .strip_prefix("pub ")
                .unwrap_or(name_line)
                .trim_end_matches(',')
                .trim()
                .to_string();

            i += 1;
            while i < lines.len() && lines[i].trim().is_empty() {
                i += 1;
            }
            if i >= lines.len() {
                break;
            }
            let level = lines[i].trim().trim_end_matches(',').to_string();

            i += 1;
            while i < lines.len() && lines[i].trim().is_empty() {
                i += 1;
            }
            if i >= lines.len() {
                break;
            }
            let desc = lines[i]
                .trim()
                .trim_start_matches('"')
                .trim_end_matches(',')
                .trim_end_matches('"')
                .to_string();

            entries.push(LintEntry {
                name_doc: name_snake.to_lowercase(),
                name_snake,
                level,
                description: desc,
                category: None,
            });
        }
        i += 1;
    }

    if let Some(start) = content.find("pub const LINT_METADATA: &[LintMetadata] = &[") {
        let after = &content[start + "pub const LINT_METADATA: &[LintMetadata] = &[".len()..];
        if let Some(end) = after.find("];") {
            let meta_block = &after[..end];
            let meta_entries: Vec<&str> = meta_block.split("LintMetadata {").skip(1).collect();
            for entry_str in meta_entries {
                let mut lint_var = String::new();
                let mut category = String::new();
                for line in entry_str.lines() {
                    let t = line.trim().trim_end_matches(',');
                    if let Some(val) = t.strip_prefix("lint:") {
                        lint_var = val.trim().to_string();
                    } else if let Some(val) = t.strip_prefix("category:") {
                        let raw = val.trim();
                        category = raw
                            .strip_prefix("LintCategory::")
                            .unwrap_or(&raw)
                            .to_string();
                    }
                }
                if !lint_var.is_empty() && !category.is_empty() {
                    for entry in &mut entries {
                        if entry.name_snake == lint_var {
                            entry.category = Some(category.clone());
                            break;
                        }
                    }
                }
            }
        }
    }

    entries
}

fn generate_readme(entries: &[LintEntry]) -> String {
    let category_order = [
        "StorageOperations",
        "Compute",
        "Memory",
        "EntryLifecycle",
        "SymbolOperations",
    ];
    let category_labels: BTreeMap<&str, &str> = [
        ("StorageOperations", "Storage Operations"),
        ("Compute", "CPU/Compute"),
        ("Memory", "Memory"),
        ("EntryLifecycle", "Entry Lifecycle"),
        ("SymbolOperations", "Symbol Operations"),
    ]
    .into_iter()
    .collect();

    let mut categorized: BTreeMap<&str, Vec<&LintEntry>> = BTreeMap::new();
    for entry in entries {
        let cat = entry.category.as_deref().unwrap_or("Other");
        categorized.entry(cat).or_default().push(entry);
    }

    let mut md = String::new();
    md.push_str("# Lint Reference\n\n");
    md.push_str("<!-- DO NOT EDIT THIS FILE BY HAND -->\n");
    md.push_str("<!-- This file is generated by `tools/generate-lint-docs`. -->\n");
    md.push_str(
        "<!-- Run `cargo run -p generate-lint-docs` from the workspace root to regenerate. -->\n\n",
    );
    md.push_str("{% hint style=\"info\" %}\n");
    md.push_str("See the [Cost Rationale](../cost_rationale.md) page for a full explanation of Soroban's metered resources and why each resource matters.\n");
    md.push_str("{% endhint %}\n\n");

    for cat in &category_order {
        if let Some(entries) = categorized.get(*cat) {
            let label = category_labels.get(cat).unwrap_or(cat);
            md.push_str(&format!("## {}\n\n", label));
            md.push_str("| Lint | Default Severity | Catches |\n");
            md.push_str("| --- | --- | --- |\n");
            for entry in entries {
                let doc_path = format!("{}.md", entry.name_doc);
                md.push_str(&format!(
                    "| [`{}`]({}) | `{}` | {} |\n",
                    entry.name_doc,
                    doc_path,
                    entry.level.to_lowercase(),
                    entry.description
                ));
            }
            md.push('\n');
        }
    }

    if let Some(entries) = categorized.get("Other") {
        md.push_str("## Other\n\n");
        md.push_str("| Lint | Default Severity | Catches |\n");
        md.push_str("| --- | --- | --- |\n");
        for entry in entries {
            let doc_path = format!("{}.md", entry.name_doc);
            md.push_str(&format!(
                "| [`{}`]({}) | `{}` | {} |\n",
                entry.name_doc,
                doc_path,
                entry.level.to_lowercase(),
                entry.description
            ));
        }
        md.push('\n');
    }

    md.push_str("{% hint style=\"info\" %}\n");
    md.push_str("Severities can be adjusted per-workspace via `budget.toml` — see the [Integration Guide](../integration.md).\n");
    md.push_str("{% endhint %}\n");

    md
}

fn generate_registry(entries: &[LintEntry]) -> String {
    let registry: Vec<serde_json::Value> = entries
        .iter()
        .map(|e| {
            serde_json::json!({
                "name": e.name_doc,
                "default_level": e.level.to_lowercase(),
                "description": e.description,
                "category": e.category.as_deref().unwrap_or("Other"),
                "docs_path": format!("docs/lints/{}.md", e.name_doc),
            })
        })
        .collect();
    serde_json::to_string_pretty(&registry).unwrap()
}

fn resolve_path(path: &str) -> PathBuf {
    let explicit = std::env::args()
        .position(|a| a == "--workspace-root")
        .and_then(|idx| std::env::args().nth(idx + 1));

    if let Some(root) = explicit {
        Path::new(&root).join(path)
    } else {
        Path::new(path).to_path_buf()
    }
}

fn main() {
    let check_mode = std::env::args().any(|a| a == "--check");

    let lib_path = resolve_path("soroban_cost_lints/src/lib.rs");
    let readme_path = resolve_path("docs/lints/README.md");
    let registry_path = resolve_path("docs/lints/lint-registry.json");

    if !lib_path.exists() {
        eprintln!(
            "Error: Cannot find soroban_cost_lints/src/lib.rs at {:?}",
            lib_path
        );
        eprintln!("Run from workspace root or pass --workspace-root <path>.");
        process::exit(1);
    }

    let content = fs::read_to_string(&lib_path).expect("Failed to read lib.rs");
    let entries = parse_lib_rs(&content);

    let readme = generate_readme(&entries);
    let registry_json = generate_registry(&entries);

    if check_mode {
        let current_readme = fs::read_to_string(&readme_path).unwrap_or_default();
        let current_registry = fs::read_to_string(&registry_path).unwrap_or_default();

        let mut exit_code = 0;
        if current_readme != readme {
            eprintln!("❌ docs/lints/README.md is out of date. Run `cargo run -p generate-lint-docs` from workspace root to regenerate.");
            exit_code = 1;
        }
        if current_registry != registry_json {
            eprintln!("❌ docs/lints/lint-registry.json is out of date. Run `cargo run -p generate-lint-docs` from workspace root to regenerate.");
            exit_code = 1;
        }
        if exit_code != 0 {
            process::exit(exit_code);
        }
        println!("✅ Lint documentation is up to date.");
    } else {
        if let Some(parent) = readme_path.parent() {
            fs::create_dir_all(parent).ok();
        }
        fs::write(&readme_path, &readme).expect("Failed to write README.md");
        println!("✅ Wrote {:?}", readme_path);

        if let Some(parent) = registry_path.parent() {
            fs::create_dir_all(parent).ok();
        }
        fs::write(&registry_path, &registry_json).expect("Failed to write lint-registry.json");
        println!("✅ Wrote {:?}", registry_path);
    }
}
