[package]
name = "soroban_cost_lints"
version = "0.1.1"
authors = ["Tollcraft Team <https://tollcraft.gitbook.io/docs>"]
description = "Dylint library providing Soroban cost-analysis lints for cargo-cost-lint"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "f6d310692116e9a527ce6d0b3526c965d9c5d7b9" }
dylint_linting = "6.0.1"

[dev-dependencies]
dylint = "6.0.1"
dylint_internal = "6.0.1"
dylint_testing = "6.0.1"

[package.metadata.rust-analyzer]
rustc_private = true
